mineralberries = {}
dofile(core.get_modpath("mineralberries").."/settings.lua")
dofile(core.get_modpath("mineralberries").."/api.lua")
--bushes
--api: register_berry(ore, ore_name, oreblock, berry_texture, bush_texture, berry_bush_texture, berries_dropped, growth_timer)
--Coal
mineralberries.register_berry("default:coal_lump",
    "Coal",
    "default:stone_with_coal", 
    "mineralberries_coal_bush_berries.png", 
    "mineralberries_bush.png", 
    "mineralberries_bush.png^mineralberries_coal_bush_berries.png",
    3, 
    300)
--Diamond
mineralberries.register_berry("default:diamond",
    "Diamond",
    "default:stone_with_diamond",
    "mineralberries_diamond_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_diamond_bush_berries.png",
    5,
    500)
--Copper
mineralberries.register_berry("default:copper_lump",
    "Copper",
    "default:stone_with_copper",
    "mineralberries_copper_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_copper_bush_berries.png",
    3,
    300)
--Gold
mineralberries.register_berry("default:gold_lump",
    "Gold",
    "default:stone_with_gold",
    "mineralberries_gold_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_gold_bush_berries.png",
    9,
    900)
--iron
mineralberries.register_berry("default:iron_lump",
    "Iron",
    "default:stone_with_iron",
    "mineralberries_iron_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_iron_bush_berries.png",
    3,
    300)
--Mese
mineralberries.register_berry("default:mese_crystal",
    "Mese",
    "default:stone_with_mese",
    "mineralberries_mese_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_mese_bush_berries.png",
    5,
    500)
--Tin
mineralberries.register_berry("default:tin_lump",
    "Tin",
    "default:stone_with_tin",
    "mineralberries_tin_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_tin_bush_berries.png",
    4,
    400)
--moreores
if core.get_modpath("moreores") then
    mineralberries.register_berry("moreores:silver_lump",
        "Silver",
        "moreores:mineral_silver",
        "mineralberries_moreores_silver_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_moreores_silver_bush_berries.png",
        4,
        400)
    mineralberries.register_berry("moreores:mithril_lump",
        "Mithril",
        "moreores:mineral_mithril",
        "mineralberries_moreores_mithril_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_moreores_mithril_bush_berries.png",
        5,
        500)
end

--technic
if core.get_modpath("technic") then
    mineralberries.register_berry("technic:chromium_lump",
        "Chromium",
        "technic:mineral_chromium",
        "mineralberries_technic_chromium_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_technic_chromium_bush_berries.png",
        5,
        500)
    mineralberries.register_berry("technic:lead_lump",
        "Lead",
        "technic:mineral_lead",
        "mineralberries_technic_lead_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_technic_lead_bush_berries.png",
        3,
        300)
    mineralberries.register_berry("technic:uranium_lump",
        "Uranium",
        "technic:mineral_uranium",
        "mineralberries_technic_uranium_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_technic_uranium_bush_berries.png",
        5,
        500)
    mineralberries.register_berry("technic:zinc_lump",
        "Zinc",
        "technic:mineral_zinc",
        "mineralberries_technic_zinc_bush_berries.png",
        "mineralberries_bush.png",
        "mineralberries_bush.png^mineralberries_technic_zinc_bush_berries.png",
        5,
        500)
end
if core.get_modpath("terumet") then
    mineralberries.register_berry("terumet:lump_raw",
    "Terumetal",
    "terumet:ore_raw",
    "mineralberries_terumetal_bush_berries.png",
    "mineralberries_bush.png",
    "mineralberries_bush.png^mineralberries_terumetal_bush_berries.png",
    5,
    500)
end